/* Generated by scripts/po2js.js from po/*.po. Do not edit. */
/* eslint-disable */

cockpit.locale(
{
 "": {
  "plural-forms": (n) => (n != 1),
  "language": "pt_BR",
  "language-direction": "ltr"
 },
 "Overview": [
  null,
  "Visão geral"
 ],
 "Snapshots": [
  null,
  "Instantâneos"
 ],
 "Schedule": [
  null,
  "Agenda"
 ],
 "Settings": [
  null,
  "Definições"
 ],
 "Toggle navigation": [
  null,
  "Alternar navegação"
 ],
 "Toggle theme": [
  null,
  "Alternar tema"
 ],
 "Connected": [
  null,
  "Ligado"
 ],
 "Refreshing…": [
  null,
  "A atualizar…"
 ],
 "Error": [
  null,
  "Erro"
 ],
 "SYSTEM PROTECTION": [
  null,
  "PROTEÇÃO DO SISTEMA"
 ],
 "Timeshift": [
  null,
  "Timeshift"
 ],
 "Create, inspect and restore system snapshots.": [
  null,
  "Criar, consultar e restaurar instantâneos do sistema."
 ],
 "Create snapshot": [
  null,
  "Criar instantâneo"
 ],
 "Refresh": [
  null,
  "Atualizar"
 ],
 "Checking Timeshift…": [
  null,
  "A verificar o Timeshift…"
 ],
 "Connecting to /usr/bin/timeshift.": [
  null,
  "A ligar ao /usr/bin/timeshift."
 ],
 "Checking": [
  null,
  "A verificar"
 ],
 "restore points": [
  null,
  "pontos de restauro"
 ],
 "Last snapshot": [
  null,
  "Último instantâneo"
 ],
 "Free space": [
  null,
  "Espaço livre"
 ],
 "Next snapshot": [
  null,
  "Próximo instantâneo"
 ],
 "snapshot storage": [
  null,
  "armazenamento de instantâneos"
 ],
 "systemd timer": [
  null,
  "temporizador systemd"
 ],
 "not scheduled": [
  null,
  "não agendado"
 ],
 "Recent snapshots": [
  null,
  "Instantâneos recentes"
 ],
 "The latest restore points on this system.": [
  null,
  "Os pontos de restauro mais recentes neste sistema."
 ],
 "View all": [
  null,
  "Ver todos"
 ],
 "Date": [
  null,
  "Data"
 ],
 "Type": [
  null,
  "Tipo"
 ],
 "Comment": [
  null,
  "Comentário"
 ],
 "Size": [
  null,
  "Tamanho"
 ],
 "Status": [
  null,
  "Estado"
 ],
 "Actions": [
  null,
  "Ações"
 ],
 "Search snapshots": [
  null,
  "Procurar instantâneos"
 ],
 "All types": [
  null,
  "Todos os tipos"
 ],
 "Scheduled": [
  null,
  "Agendado"
 ],
 "On-demand": [
  null,
  "Sob pedido"
 ],
 "No snapshots found": [
  null,
  "Não foram encontrados instantâneos"
 ],
 "Try changing the search or filter.": [
  null,
  "Tente alterar a pesquisa ou o filtro."
 ],
 "No snapshots detected.": [
  null,
  "Não foram detetados instantâneos."
 ],
 "Restore": [
  null,
  "Restaurar"
 ],
 "Delete": [
  null,
  "Eliminar"
 ],
 "Automatic snapshots": [
  null,
  "Instantâneos automáticos"
 ],
 "Uses Timeshift's native scheduler: an hourly check that creates a snapshot when a level is due.": [
  null,
  "Usa o agendador nativo do Timeshift: uma verificação horária que cria um instantâneo quando um nível está em devido."
 ],
 "Enable automatic snapshots": [
  null,
  "Ativar instantâneos automáticos"
 ],
 "Hourly": [
  null,
  "Horário"
 ],
 "Daily": [
  null,
  "Diário"
 ],
 "Weekly": [
  null,
  "Semanal"
 ],
 "Monthly": [
  null,
  "Mensal"
 ],
 "At boot": [
  null,
  "No arranque"
 ],
 "kept": [
  null,
  "mantidos"
 ],
 "Retention count": [
  null,
  "Contagem de retenção"
 ],
 "Retention": [
  null,
  "Retenção"
 ],
 "Retention counts are written to the Timeshift config and enforced by Timeshift through its tag system. Boot snapshots are created roughly 10 minutes after startup.": [
  null,
  "As contagens de retenção são escritas na configuração do Timeshift e aplicadas pelo Timeshift através do seu sistema de tags. Os instantâneos de arranque são criados cerca de 10 minutos após o arranque do sistema."
 ],
 "Save schedule": [
  null,
  "Guardar agenda"
 ],
 "Timer status": [
  null,
  "Estado do temporizador"
 ],
 "Live systemd state for the Timeshift scheduler unit.": [
  null,
  "Estado systemd em tempo real para a unidade de agendamento do Timeshift."
 ],
 "Checking…": [
  null,
  "A verificar…"
 ],
 "Waiting for output…": [
  null,
  "A aguardar saída…"
 ],
 "Working…": [
  null,
  "A trabalhar…"
 ],
 "Preparing Timeshift": [
  null,
  "A preparar o Timeshift"
 ],
 "Cancel": [
  null,
  "Cancelar"
 ],
 "Close": [
  null,
  "Fechar"
 ],
 "Enable at least one snapshot level.": [
  null,
  "Ative pelo menos um nível de instantâneo."
 ],
 "Schedule enabled (timeshift checks hourly, snapshots when a level is due).": [
  null,
  "Agenda ativada (o timeshift verifica de hora em hora e cria instantâneos quando um nível está em devido)."
 ],
 "Timeshift native scheduling enabled.": [
  null,
  "Agendamento nativo do Timeshift ativado."
 ],
 "Schedule disabled.": [
  null,
  "Agenda desativada."
 ],
 "Schedule configuration failed.": [
  null,
  "Falha ao configurar a agenda."
 ],
 "enabled: $0": [
  null,
  "ativado: $0"
 ],
 "active: $0": [
  null,
  "ativo: $0"
 ],
 "next: $0": [
  null,
  "próximo: $0"
 ],
 "unit: $0": [
  null,
  "unidade: $0"
 ],
 "executable: $0": [
  null,
  "executável: $0"
 ],
 "Waiting": [
  null,
  "A aguardar"
 ],
 "Not scheduled": [
  null,
  "Não agendado"
 ],
 "Timeshift integration": [
  null,
  "Integração do Timeshift"
 ],
 "Live information from the installed host executable.": [
  null,
  "Informações em tempo real do executável instalado no sistema."
 ],
 "Executable": [
  null,
  "Executável"
 ],
 "Version": [
  null,
  "Versão"
 ],
 "Mode": [
  null,
  "Modo"
 ],
 "Privilege": [
  null,
  "Privilégio"
 ],
 "Snapshot engine. RSYNC works on most filesystems; BTRFS requires a BTRFS volume.": [
  null,
  "Motor de instantâneos. O RSYNC funciona na maioria dos sistemas de ficheiros; o BTRFS requer um volume BTRFS."
 ],
 "RSYNC works on most filesystems; BTRFS uses native snapshots (available on this system).": [
  null,
  "O RSYNC funciona na maioria dos sistemas de ficheiros; o BTRFS usa instantâneos nativos (disponível neste sistema)."
 ],
 "RSYNC works on most filesystems. BTRFS is unavailable — the system is not on a BTRFS volume.": [
  null,
  "O RSYNC funciona na maioria dos sistemas de ficheiros. O BTRFS não está disponível — o sistema não está num volume BTRFS."
 ],
 "Device: $0 · UUID: $1 · Mode: $2 · Status: $3": [
  null,
  "Dispositivo: $0 · UUID: $1 · Modo: $2 · Estado: $3"
 ],
 "Backup device": [
  null,
  "Dispositivo de backup"
 ],
 "Choose which Linux device stores the snapshots. Matches Timeshift's Settings ▸ Location.": [
  null,
  "Escolha qual o dispositivo Linux que guarda os instantâneos. Corresponde a Definições ▸ Localização do Timeshift."
 ],
 "Scanning devices…": [
  null,
  "A analisar dispositivos…"
 ],
 "Note": [
  null,
  "Nota"
 ],
 "Snapshots are stored on the selected device under": [
  null,
  "Os instantâneos são guardados no dispositivo selecionado em"
 ],
 ". A separate or external device is recommended.": [
  null,
  ". É recomendado um dispositivo separado ou externo."
 ],
 "Excluded items": [
  null,
  "Itens excluídos"
 ],
 "Rsync filter paths skipped during snapshots (Timeshift Filters). One pattern per line.": [
  null,
  "Caminhos de filtro rsync ignorados durante os instantâneos (filtros do Timeshift). Um padrão por linha."
 ],
 "Save exclusions": [
  null,
  "Guardar exclusões"
 ],
 "Exclusions saved.": [
  null,
  "Exclusões guardadas."
 ],
 "Exclusion list updated.": [
  null,
  "Lista de exclusões atualizada."
 ],
 "Home directories are already excluded by default. Add extra paths to skip, e.g.": [
  null,
  "As diretorias pessoais já estão excluídas por predefinição. Adicione caminhos extra a ignorar, p. ex."
 ],
 "Storage": [
  null,
  "Armazenamento"
 ],
 "Loading…": [
  null,
  "A carregar…"
 ],
 "Danger zone": [
  null,
  "Zona de perigo"
 ],
 "These actions are destructive and cannot be undone.": [
  null,
  "Estas ações são destrutivas e não podem ser anuladas."
 ],
 "Delete all snapshots": [
  null,
  "Eliminar todos os instantâneos"
 ],
 "Delete every Timeshift snapshot?": [
  null,
  "Eliminar todos os instantâneos do Timeshift?"
 ],
 "This action cannot be undone.": [
  null,
  "Esta ação não pode ser anulada."
 ],
 "Delete all": [
  null,
  "Eliminar todos"
 ],
 "Deleting all snapshots": [
  null,
  "A eliminar todos os instantâneos"
 ],
 "All snapshots deleted successfully.": [
  null,
  "Todos os instantâneos foram eliminados com sucesso."
 ],
 "No eligible Linux devices found (ext4/xfs/btrfs). Press Refresh to rescan.": [
  null,
  "Não foram encontrados dispositivos Linux elegíveis (ext4/xfs/btrfs). Prima Atualizar para voltar a analisar."
 ],
 "Current backup device": [
  null,
  "Dispositivo de backup atual"
 ],
 "Set as backup device": [
  null,
  "Definir como dispositivo de backup"
 ],
 "mounted": [
  null,
  "montado"
 ],
 "not mounted": [
  null,
  "não montado"
 ],
 "Device has no UUID and cannot be used by Timeshift.": [
  null,
  "O dispositivo não tem UUID e não pode ser usado pelo Timeshift."
 ],
 "Backup device set to $0.": [
  null,
  "Dispositivo de backup definido para $0."
 ],
 "Timeshift not configured": [
  null,
  "Timeshift não configurado"
 ],
 "No backup device selected. Configure Timeshift to enable protection.": [
  null,
  "Nenhum dispositivo de backup selecionado. Configure o Timeshift para ativar a proteção."
 ],
 "Timeshift reports a problem": [
  null,
  "O Timeshift reporta um problema"
 ],
 "Timeshift status: $0": [
  null,
  "Estado do Timeshift: $0"
 ],
 "No snapshots detected": [
  null,
  "Não foram detetados instantâneos"
 ],
 "Timeshift is installed, but no restore points were found.": [
  null,
  "O Timeshift está instalado, mas não foram encontrados pontos de restauro."
 ],
 "System protected": [
  null,
  "Sistema protegido"
 ],
 "$0 restore point available": [null,"$0 ponto de restauro disponível","$0 pontos de restauro disponíveis"],
 "Enabled": [
  null,
  "Ativado"
 ],
 "Manual only": [
  null,
  "Apenas manual"
 ],
 "$0 is installed but has no backup device configured. Open the Timeshift app (\"sudo timeshift-gtk\") to select a backup device, then refresh.": [
  null,
  "$0 está instalado mas não tem dispositivo de backup configurado. Abra a aplicação Timeshift (\"sudo timeshift-gtk\") para selecionar um dispositivo de backup e depois atualize."
 ],
 "Timeshift is not configured to use a backup device.": [
  null,
  "O Timeshift não está configurado para usar um dispositivo de backup."
 ],
 "Unable to communicate with $0. $1": [
  null,
  "Não foi possível comunicar com $0. $1"
 ],
 "Timeshift communication failed.": [
  null,
  "Falha na comunicação com o Timeshift."
 ],
 "Detected": [
  null,
  "Detetado"
 ],
 "No device information returned.": [
  null,
  "Não foram devolvidas informações do dispositivo."
 ],
 "Unable to load device information.": [
  null,
  "Não foi possível carregar as informações do dispositivo."
 ],
 "✔ found and executable": [
  null,
  "✔ encontrado e executável"
 ],
 "✘ not found or not executable": [
  null,
  "✘ não encontrado ou não executável"
 ],
 "Manual system snapshot": [
  null,
  "Instantâneo manual do sistema"
 ],
 "Timeshift will create a new restore point using its configured storage.": [
  null,
  "O Timeshift irá criar um novo ponto de restauro usando o armazenamento configurado."
 ],
 "Snapshot created successfully.": [
  null,
  "Instantâneo criado com sucesso."
 ],
 "Creating snapshot": [
  null,
  "A criar instantâneo"
 ],
 "Restore snapshot": [
  null,
  "Restaurar instantâneo"
 ],
 "Restore the system to snapshot $0?": [
  null,
  "Restaurar o sistema para o instantâneo $0?"
 ],
 "What will happen": [
  null,
  "O que vai acontecer"
 ],
 "System files and settings are restored to the state of this snapshot.": [
  null,
  "Os ficheiros e definições do sistema são restaurados para o estado deste instantâneo."
 ],
 "Boot files and EFI are handled automatically by Timeshift.": [
  null,
  "Os ficheiros de arranque e a EFI são tratados automaticamente pelo Timeshift."
 ],
 "User data under /home is excluded by default and remains untouched.": [
  null,
  "Os dados do utilizador em /home estão excluídos por predefinição e permanecem intocados."
 ],
 "Timeshift reinstalls the bootloader automatically if needed.": [
  null,
  "O Timeshift reinstala o carregador de arranque automaticamente se necessário."
 ],
 "This changes the system and requires a reboot to complete.": [
  null,
  "Isto altera o sistema e requer um reinício para concluir."
 ],
 "Restoring snapshot": [
  null,
  "A restaurar instantâneo"
 ],
 "Restore command completed.": [
  null,
  "Comando de restauro concluído."
 ],
 "Delete snapshot": [
  null,
  "Eliminar instantâneo"
 ],
 "Delete $0?": [
  null,
  "Eliminar $0?"
 ],
 "This cannot be undone.": [
  null,
  "Isto não pode ser anulado."
 ],
 "Deleting snapshot": [
  null,
  "A eliminar instantâneo"
 ],
 "Snapshot deleted successfully.": [
  null,
  "Instantâneo eliminado com sucesso."
 ],
 "Operation completed successfully": [
  null,
  "Operação concluída com sucesso"
 ],
 "Snapshot completed": [
  null,
  "Instantâneo concluído"
 ],
 "Operation failed": [
  null,
  "Operação falhou"
 ],
 "Timeshift returned an error": [
  null,
  "O Timeshift devolveu um erro"
 ],
 "$0 live output update": [null,"$0 atualização de saída em direto","$0 atualizações de saída em direto"],
 "Mounting snapshot storage": [
  null,
  "A montar o armazenamento de instantâneos"
 ],
 "Copying system data": [
  null,
  "A copiar dados do sistema"
 ],
 "Updating boot files": [
  null,
  "A atualizar os ficheiros de arranque"
 ],
 "Unmounting storage": [
  null,
  "A desmontar o armazenamento"
 ],
 "Could not configure systemd: $0": [
  null,
  "Não foi possível configurar o systemd: $0"
 ],
 "Could not save exclusions: $0": [
  null,
  "Não foi possível guardar as exclusões: $0"
 ],
 "Could not save exclusions.": [
  null,
  "Não foi possível guardar as exclusões."
 ],
 "BTRFS mode is unavailable on this system.": [
  null,
  "O modo BTRFS não está disponível neste sistema."
 ],
 "Snapshot mode set to $0.": [
  null,
  "Modo de instantâneo definido para $0."
 ],
 "Could not save snapshot mode: $0": [
  null,
  "Não foi possível guardar o modo de instantâneo: $0"
 ],
 "Could not save snapshot mode.": [
  null,
  "Não foi possível guardar o modo de instantâneo."
 ],
 "Browse and manage available restore points.": [
  null,
  "Consultar e gerir os pontos de restauro disponíveis."
 ],
 "Configure automatic system snapshots.": [
  null,
  "Configurar instantâneos automáticos do sistema."
 ],
 "Inspect Timeshift integration and storage.": [
  null,
  "Consultar a integração e o armazenamento do Timeshift."
 ]
}
);
