"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const PO_DIR = path.join(ROOT, "po");
const RTL_LANGS = ["ar", "fa", "he", "ur"];

function unescapePo(value) {
  return value
    .replace(/\\n/g, "\n")
    .replace(/\\t/g, "\t")
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, "\\");
}

function parsePo(text) {
  const lines = String(text || "").split(/\r?\n/);
  const entries = [];
  let cur = null;
  let field = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) continue;

    const keyMatch = line.match(/^(msgid(?:_plural)?|msgstr(?:\[\d+\])?)\s*(.*)$/);
    const contMatch = line.match(/^"(.*)"\s*$/);

    if (keyMatch) {
      const key = keyMatch[1];
      const rest = keyMatch[2];
      if (key === "msgid" && cur) {
        entries.push(cur);
        cur = null;
      }
      if (!cur) {
        cur = { msgid: "", msgstr: [] };
      }
      if (key === "msgid") {
        cur.msgid += unescapePo(rest.replace(/^"(.*)"$/, "$1"));
        field = "msgid";
      } else if (key === "msgid_plural") {
        cur.msgid += "\u0000" + unescapePo(rest.replace(/^"(.*)"$/, "$1"));
        field = "msgid_plural";
      } else {
        const idxMatch = key.match(/\[(\d+)\]/);
        const idx = idxMatch ? Number(idxMatch[1]) : 0;
        cur.msgstr[idx] = unescapePo(rest.replace(/^"(.*)"$/, "$1"));
        field = "msgstr";
      }
    } else if (contMatch) {
      const value = unescapePo(contMatch[1]);
      if (field === "msgid") {
        cur.msgid += value;
      } else if (field === "msgid_plural") {
        const nul = cur.msgid.indexOf("\u0000");
        cur.msgid = cur.msgid.slice(0, nul) + "\u0000" + (cur.msgid.slice(nul + 1) + value);
      } else if (field === "msgstr") {
        const idx = cur.msgstr.length - 1;
        if (idx >= 0) cur.msgstr[idx] += value;
      }
    }
  }
  if (cur) entries.push(cur);

  const result = [];
  for (const e of entries) {
    const nul = e.msgid.indexOf("\u0000");
    const isPlural = nul !== -1;
    const msgid = isPlural ? e.msgid.slice(0, nul) : e.msgid;
    const pluralMsgid = isPlural ? e.msgid.slice(nul + 1) : null;
    if (msgid === "") {
      const headerText = e.msgstr[0] || "";
      result.push({
        header: true,
        pluralForms: headerText.match(/Plural-Forms:\s*([^\n]+)/)?.[1] || "",
        language: headerText.match(/Language:\s*(\S+)/)?.[1] || ""
      });
      continue;
    }
    result.push({ msgid, msgstr: e.msgstr, plural: isPlural, pluralMsgid });
  }
  return result;
}

function pluralExpr(headerText) {
  const m = String(headerText || "").match(/nplurals=[1-9];\s*plural=([^;]+);?/);
  if (!m) {
    throw new Error(`bad plural-forms header: ${JSON.stringify(headerText)}`);
  }
  let expr = m[1].trim();
  if (/^\(.*\)$/.test(expr)) expr = expr.slice(1, -1);
  return `(n) => (${expr})`;
}

function json(value) {
  return JSON.stringify(value);
}

function buildLocaleData(entries, language) {
  const header = entries.find(e => e.header);
  if (!header) throw new Error(`no header entry in ${language}.po`);
  const dir = RTL_LANGS.includes(language) ? "rtl" : "ltr";

  const chunks = [];
  chunks.push("{\n");
  chunks.push(' "": {\n');
  chunks.push(`  "plural-forms": ${pluralExpr(header.pluralForms)},\n`);
  chunks.push(`  "language": ${json(language)},\n`);
  chunks.push(`  "language-direction": ${json(dir)}\n`);
  chunks.push(" }");

  for (const e of entries) {
    if (e.header) continue;
    if (e.plural) {
      const msgstr = e.msgstr.length
        ? [null, ...e.msgstr]
        : [null, ""];
      chunks.push(`,\n ${json(e.msgid)}: ${json(msgstr)}`);
    } else {
      chunks.push(`,\n ${json(e.msgid)}: [\n  null,\n  ${json(e.msgstr[0] || "")}\n ]`);
    }
  }
  chunks.push("\n}");

  return chunks.join("");
}

function localeFileNames(language) {
  const code = String(language).split(/[-_]/)[0].toLowerCase();
  const names = [language, code];
  if (code === "pt") names.push("pt_BR");
  return [...new Set(names)];
}

function makePoJs(language, data) {
  return [
    "/* Generated by scripts/po2js.js from po/*.po. Do not edit. */",
    "/* eslint-disable */",
    "",
    "cockpit.locale(",
    data,
    ");",
    ""
  ].join("\n");
}

function main() {
  const linguas = fs
    .readFileSync(path.join(PO_DIR, "LINGUAS"), "utf8")
    .split(/\s+/)
    .filter(Boolean);

  const written = [];
  for (const lang of linguas) {
    const poFile = path.join(PO_DIR, `${lang}.po`);
    if (!fs.existsSync(poFile)) {
      console.error(`missing ${poFile} (listed in LINGUAS)`);
      process.exit(2);
    }
    const entries = parsePo(fs.readFileSync(poFile, "utf8"));
    for (const name of localeFileNames(lang)) {
      const data = buildLocaleData(entries, name);
      const out = path.join(ROOT, `po.${name}.js`);
      fs.writeFileSync(out, makePoJs(name, data));
      written.push(`po.${name}.js`);
    }
  }

  console.log(`wrote ${written.join(", ")}`);
}

module.exports = { parsePo, pluralExpr, buildLocaleData, localeFileNames };
if (require.main === module) main();